-- MASQ. shop schema (Postgres)
--
-- Money is stored in KOBO as integers, never naira as floats. 0.1 + 0.2 is not
-- 0.3 in binary floating point, and a shop that rounds a fraction of a kobo per
-- line eventually disagrees with its payment provider about what it charged.
-- Paystack's API also takes and returns kobo, so this keeps one unit end to end.
--
-- Every statement is IF NOT EXISTS, so this file runs on every boot and only
-- ever adds what is missing.

CREATE TABLE IF NOT EXISTS products (
  id          TEXT        PRIMARY KEY,
  name        TEXT        NOT NULL,
  price_kobo  INTEGER     NOT NULL CHECK (price_kobo > 0),
  img         TEXT        NOT NULL,
  badge       TEXT,
  is_extra    BOOLEAN     NOT NULL DEFAULT FALSE,
  -- Postgres has no insertion order to fall back on, so display order is kept
  -- explicitly rather than hoped for.
  position    INTEGER     NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per sellable thing. A size is not a property of a product, it is a
-- separate thing with its own stock count — "THE FACE TEE" is never in stock,
-- "THE FACE TEE, size M" is.
CREATE TABLE IF NOT EXISTS variants (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  TEXT    NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  size        TEXT    NOT NULL,
  stock       INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  UNIQUE (product_id, size)
);

CREATE TABLE IF NOT EXISTS customers (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- status:
--   pending    stock is held; the customer is on (or left) Paystack's page
--   paid       Paystack confirmed the full amount
--   failed     Paystack said the charge failed; stock returned
--   abandoned  never paid; stock returned by the sweeper
--   refund_due paid AFTER the order was given up on, and the stock had
--              already gone to someone else. The customer has been charged for
--              something that cannot be sent, so a person must refund them.
--
-- Stock is held at `pending` so two people cannot both buy the last jacket
-- while one of them is still on Paystack's page.
CREATE TABLE IF NOT EXISTS orders (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference      TEXT        NOT NULL UNIQUE,
  customer_id    INTEGER     REFERENCES customers(id),
  email          TEXT        NOT NULL,
  status         TEXT        NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending','paid','failed','abandoned','refund_due')),
  subtotal_kobo  INTEGER     NOT NULL CHECK (subtotal_kobo > 0),
  currency       TEXT        NOT NULL DEFAULT 'NGN',
  paystack_id    TEXT,
  paid_at        TIMESTAMPTZ,
  fulfilled_at   TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Line items keep their own copy of name and price. A product's price may
-- change next week; what this customer was charged must not.
CREATE TABLE IF NOT EXISTS order_items (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id      TEXT    NOT NULL,
  variant_id      INTEGER NOT NULL,
  name            TEXT    NOT NULL,
  size            TEXT    NOT NULL,
  unit_price_kobo INTEGER NOT NULL CHECK (unit_price_kobo > 0),
  qty             INTEGER NOT NULL CHECK (qty > 0)
);

-- Every webhook Paystack sends, recorded before it is acted on. Paystack
-- retries, so the same event arrives more than once; the UNIQUE event_id is
-- what makes handling it idempotent.
CREATE TABLE IF NOT EXISTS webhook_events (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id     TEXT        NOT NULL UNIQUE,
  event_type   TEXT        NOT NULL,
  reference    TEXT,
  payload      TEXT        NOT NULL,
  processed_at TIMESTAMPTZ,
  received_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Small pieces of shop state that must survive a restart and cannot live in
-- the host's environment variables. Today: the admin password hash, when it
-- was set through the browser rather than ADMIN_PASSWORD_HASH.
CREATE TABLE IF NOT EXISTS settings (
  key        TEXT        PRIMARY KEY,
  value      TEXT        NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at);
CREATE INDEX IF NOT EXISTS idx_items_order           ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_variants_product      ON variants(product_id);
